🐛 Correcting Technical SLA reporting that not displayed
Fatal error: Unsupported operand types in /srv/eyesofnetwork/eonweb/include/function.php on line 1180

This error was due to 2 dimentions array retriving with sql request, line 1180 try to add array to int value.